# see: https://packetstormsecurity.com/files/18307/nmap-services.html
title = "Default services to scan"

[ftp]
  nmap-service-names = [
    TODO
  ]

  ["ftp.nmap"]
    cmd = "TODO"

[http]
  nmap-service-names = [
    "http",
    "http-alt"
  ]

  ["http.nmap"]
    cmd = "TODO"

  ["http.nikto"]
    cmd = "TODO"

  ["http.gobuster"]
    cmd = "TODO"

  recommendations = [
    TODO
  ]

[smb]
  nmap-service-names = [
    TODO
  ]

  ["smb.nmap"]
    cmd = "TODO"

  ["smb.enum4linux"]
    cmd = "TODO"

  recommendations = [
    TODO
  ]
